import Willington from "./images/WillingtonSolarFarm.jpeg";
import Culcairn from "./images/Culcairn.jpeg";
import Bluegrass from "./images/Bluegrass.jpeg";
import Walla from "./images/Walla.jpeg";
import Edenvale from "./images/Edenvale.jpeg";
import Everleigh from "./images/Everleigh.jpeg";
import Fraser from "./images/Fraser.jpeg";
import Richmond from "./images/Richmond.jpeg";
import Kiamal from "./images/Kiamal.jpeg";
import Wughnu from "./images/Wughnu.jpeg";
import Blacktop from "./images/Blacktop.jpeg";
import Deniliquin from "./images/Deniliquin.jpeg";
import Direk from "./images/Direk.jpeg";
import Finley from "./images/Finley.jpeg";
import Whylla from "./images/Whylla.jpeg";
import Foster from "./images/Foster.jpeg";
import Jindera from "./images/Jindera.jpeg";
import Penfield from "./images/Penfield.jpeg";

// export const combinedData = [
//   // Sta
//   {
//     id: 1,
//     type: "solar",
//     title: "BLUEGRASS",
//     voltage: "33kV",
//     description: "SOLAR FARM SUBSTATION",
//     img: renewable,
//   },
//   {
//     id: 2,
//     type: "solar",
//     title: "CULCAIRN",
//     voltage: "33kV",
//     description: "SOLAR FARM SUBSTATION",
//     img: renewable,
//   },
//   {
//     id: 3,
//     type: "solar",
//     title: "EDENVALE",
//     voltage: "275kV",
//     description: "SOLAR FARM SUBSTATION",
//     img: renewable,
//   },
//   {
//     id: 4,
//     type: "solar",
//     title: "EVERLEIGH",
//     voltage: "275kV",
//     description: "SOLAR FARM SUBSTATION",
//     img: renewable,
//   },
//   {
//     id: 5,
//     type: "solar",
//     title: "FRASER",
//     voltage: "33kV",
//     description: "SOLAR FARM SUBSTATION",
//     img: renewable,
//   },
//   {
//     id: 6,
//     type: "solar",
//     title: "KIAMAL",
//     voltage: "220kV",
//     description: "SOLAR FARM SUBSTATION",
//     img: renewable,
//   },
//   {
//     id: 7,
//     type: "solar",
//     title: "RICHMOND",
//     voltage: "330/33kV",
//     description: "SOLAR FARM SUBSTATION",
//     img: renewable,
//   },
//   {
//     id: 8,
//     type: "solar",
//     title: "RICHMOND",
//     voltage: "33kV",
//     description: "SOLAR SWITCHING SUBSTATION",
//     img: renewable,
//   },
//   {
//     id: 9,
//     type: "solar",
//     title: "WALLA WALLA",
//     voltage: "33kV",
//     description: "SOLAR FARM SUBSTATION",
//     img: renewable,
//   },
//   {
//     id: 10,
//     type: "solar",
//     title: "WALL WALL HF",
//     voltage: "33kV",
//     description: "HARMONIC FILTER SUBSTATION",
//     img: renewable,
//   },
//   {
//     id: 11,
//     type: "solar",
//     title: "WELLINGTON",
//     voltage: "330kV",
//     description: "SOLAR FARM SUBSTATION",
//     img: renewable,
//   },
//   {
//     id: 12,
//     type: "solar",
//     title: "WUGHNU",
//     voltage: "33kV",
//     description: "SOLAR FARM SUBSTATION",
//     img: renewable,
//   },

//   // Battery Data
//   {
//     id: 13,
//     type: "battery",
//     title: "BLACKTOP",
//     voltage: "100MW",
//     description: "BESS",
//     img: renewable,
//   },
//   {
//     id: 14,
//     type: "battery",
//     title: "DENILIQUIN",
//     voltage: "100MW",
//     description: "BESS",
//     img: renewable,
//   },
//   {
//     id: 15,
//     type: "battery",
//     title: "DIREK",
//     voltage: "20MW",
//     description: "BESS",
//     img: renewable,
//   },
//   {
//     id: 16,
//     type: "battery",
//     title: "FINLEY",
//     voltage: "100MW",
//     description: "BESS",
//     img: renewable,
//   },
//   {
//     id: 17,
//     type: "battery",
//     title: "FOSTER",
//     voltage: "70MW",
//     description: "BESS",
//     img: renewable,
//   },
//   {
//     id: 18,
//     type: "battery",
//     title: "JINDERA",
//     voltage: "250MW",
//     description: "BESS",
//     img: renewable,
//   },
//   {
//     id: 19,
//     type: "battery",
//     title: "PENFIELD",
//     voltage: "20MW",
//     description: "BESS",
//     img: renewable,
//   },
//   {
//     id: 20,
//     type: "battery",
//     title: "WHYLAA",
//     voltage: "100MW",
//     description: "BESS",
//     img: renewable,
//   },

//   // Wind Farm Data
//   {
//     id: 21,
//     type: "wind",
//     title: "BOOMER",
//     voltage: "275kV",
//     description: "WIND FARM SUBSTATION",
//     img: renewable,
//   },
//   {
//     id: 22,
//     type: "wind",
//     title: "BOOMER",
//     voltage: "275kV",
//     description: "WIND FARM SWITCHING SUBSTATION",
//     img: renewable,
//   },
//   // Add more objects as needed
// ];

export const combinedData = [
  {
    id: 1,
    type: "solar",
    title: "Bluegrass Solar Farm",
    img: Bluegrass,
    description: `In Chinchilla, Australia, a significant solar power project is currently under construction, covering an expansive area of 552 hectares. This project features a one-axis tracker system and is designed to achieve a peak power output of 200 MWp and a nominal power of 148 MWn. Once operational, the plant is expected to produce approximately 420,000 MWh of electricity annually. This output will substantially reduce carbon emissions, avoiding around 320,000 tons of CO₂ each year. Additionally, the generated power will be sufficient to supply electricity to approximately 80,000 households, marking a considerable contribution to sustainable energy in the region.`,
    location: "Chinchilla, Australia",
    Country: "Australia",
    Region: "Chinchilla",
    Area: "552ha",
    Project_status: "In Construction",
    System_type: "One Axis Tracker",
    Peak_power: "200MWp",
    Nominal_power: "148MWn",
    Annual_production: "420,000MWh/year",
    Tons_of_CO2_avoided: "320,000tons CO₂/year",
    Households_supplied: "80,000",
  },
  {
    id: 2,
    type: "solar",
    title: "Culcairn Solar Farm",
    img: Culcairn,
    description: `In Riverina, Australia, a significant solar power project is currently under construction, covering an expansive area of 1000 hectares. This project features a one-axis tracker system and is designed to achieve a peak power output of 350 MWp and a nominal power of 190 MWn. Once operational, the plant is expected to produce approximately 420,000 MWh of electricity annually. This output will substantially reduce carbon emissions, avoiding around 320,000 tons of CO₂ each year. Additionally, the generated power will be sufficient to supply electricity to approximately 80,000 households, marking a considerable contribution to sustainable energy in the region.`,
    location: "Riverina, Australia",
    Country: "Australia",
    Region: "Riverina",
    Area: "1000ha",
    Project_status: "In Construction",
    System_type: "One Axis Tracker",
    Peak_power: "350MWp",
    Nominal_power: "190MWn",
    Annual_production: "420,000MWh/year",
    Tons_of_CO2_avoided: "320,000tons CO₂/year",
    Households_supplied: "80,000",
  },
  {
    id: 3,
    type: "solar",
    title: "Willington Solar Farm",
    img: Willington,
    description: `In Goolma Road, Australia, a significant solar power project is currently under construction, covering an expansive area of 1000 hectares. This project features a one-axis tracker system and is designed to achieve a peak power output of 200 MWp and a nominal power of 148 MWn. Once operational, the plant is expected to produce approximately 435,000 MWh of electricity annually. This output will substantially reduce carbon emissions, avoiding around 320,000 tons of CO₂ each year. Additionally, the generated power will be sufficient to supply electricity to approximately 72,500 households, marking a considerable contribution to sustainable energy in the region.`,
    location: "Goolma Road, Australia",
    Country: "Australia",
    Region: "Goolma Road",
    Area: "1000ha",
    Project_status: "In Construction",
    System_type: "One Axis Tracker",
    Peak_power: "200MWp",
    Nominal_power: "148MWn",
    Annual_production: "435,000MWh/year",
    Tons_of_CO2_avoided: "320,000tons CO₂/year",
    Households_supplied: "72,500",
  },
  {
    id: 4,
    type: "solar",
    title: "Walla Walla Solar Farm",
    img: Walla,
    description: `In Chinchilla, Australia, a significant solar power project is currently under construction, covering an expansive area of 421 hectares. This project features a one-axis tracker system and is designed to achieve a peak power output of 200 MWp and a nominal power of 148 MWn. Once operational, the plant is expected to produce approximately 740,000 MWh of electricity annually. This output will substantially reduce carbon emissions, avoiding around 520,000 tons of CO₂ each year. Additionally, the generated power will be sufficient to supply electricity to approximately 90,000 households, marking a considerable contribution to sustainable energy in the region.`,
    location: "Chinchilla, Australia",
    Country: "Australia",
    Region: "Chinchilla",
    Area: "421ha",
    Project_status: "In Construction",
    System_type: "One Axis Tracker",
    Peak_power: "200MWp",
    Nominal_power: "148MWn",
    Annual_production: "740,000MWh/year",
    Tons_of_CO2_avoided: "520,000tons CO₂/year",
    Households_supplied: "90,000",
  },
  {
    id: 5,
    type: "solar",
    title: "Edenvale Solar Farm",
    img: Edenvale,
    description: `In Queensland, Australia, a significant solar power project is currently under construction, covering an expansive area of 428 hectares. This project features a one-axis tracker system and is designed to achieve a peak power output of 200 MWp and a nominal power of 148 MWn. Once operational, the plant is expected to produce approximately 420,000 MWh of electricity annually. This output will substantially reduce carbon emissions, avoiding around 320,000 tons of CO₂ each year. Additionally, the generated power will be sufficient to supply electricity to approximately 80,000 households, marking a considerable contribution to sustainable energy in the region.`,
    location: "Queensland, Australia",
    Country: "Australia",
    Region: "Queensland",
    Area: "428ha",
    Project_status: "In Construction",
    System_type: "One Axis Tracker",
    Peak_power: "200MWp",
    Nominal_power: "148MWn",
    Annual_production: "420,000MWh/year",
    Tons_of_CO2_avoided: "320,000tons CO₂/year",
    Households_supplied: "80,000",
  },
  {
    id: 6,
    type: "solar",
    title: "Everleigh Solar Farm",
    img: Everleigh,
    description: `In Queensland, Australia, a significant solar power project is currently under construction, covering an expansive area of 209 hectares. This project features a one-axis tracker system and is designed to achieve a peak power output of 139 MWp and a nominal power of 80 MWn. Once operational, the plant is expected to produce approximately 420,000 MWh of electricity annually. This output will substantially reduce carbon emissions, avoiding around 320,000 tons of CO₂ each year. Additionally, the generated power will be sufficient to supply electricity to approximately 40,000 households, marking a considerable contribution to sustainable energy in the region.`,
    location: "Queensland, Australia",
    Country: "Australia",
    Region: "Queensland",
    Area: "209ha",
    Project_status: "In Construction",
    System_type: "One Axis Tracker",
    Peak_power: "139MWp",
    Nominal_power: "80MWn",
    Annual_production: "420,000MWh/year",
    Tons_of_CO2_avoided: "320,000tons CO₂/year",
    Households_supplied: "40,000",
  },

  {
    id: 7,
    type: "solar",
    title: "Fraser Solar Farm",
    img: Fraser,
    description: `In Glengarry north, Australia, a significant solar power project is currently under construction, covering an expansive area of 840 hectares. This project features a one-axis tracker system and is designed to achieve a peak power output of 77 MWp and a nominal power of 59 MWn. Once operational, the plant is expected to produce approximately 420,000 MWh of electricity annually. This output will substantially reduce carbon emissions, avoiding around 320,000 tons of CO₂ each year. Additionally, the generated power will be sufficient to supply electricity to approximately 80,000 households, marking a considerable contribution to sustainable energy in the region.`,
    location: "Glengarry north, Australia",
    Country: "Australia",
    Region: "Glengarry north",
    Area: "840ha",
    Project_status: "In Construction",
    System_type: "One Axis Tracker",
    Peak_power: "77MWp",
    Nominal_power: "59MWn",
    Annual_production: "420,000MWh/year",
    Tons_of_CO2_avoided: "320,000tons CO₂/year",
    Households_supplied: "80,000",
  },
  {
    id: 8,
    type: "solar",
    title: "Richmond Solar Farm",
    img: Richmond,
    description: `In Chinchilla, Australia, a significant solar power project is currently under construction, covering an expansive area of 1000 hectares. This project features a one-axis tracker system and is designed to achieve a peak power output of 200 MWp and a nominal power of 148 MWn. Once operational, the plant is expected to produce approximately 420,000 MWh of electricity annually. This output will substantially reduce carbon emissions, avoiding around 320,000 tons of CO₂ each year. Additionally, the generated power will be sufficient to supply electricity to approximately 80,000 households, marking a considerable contribution to sustainable energy in the region.`,
    location: "Chinchilla, Australia",
    Country: "Australia",
    Region: "Chinchilla",
    Area: "1000ha",
    Project_status: "In Construction",
    System_type: "One Axis Tracker",
    Peak_power: "200MWp",
    Nominal_power: "148MWn",
    Annual_production: "420,000MWh/year",
    Tons_of_CO2_avoided: "320,000tons CO₂/year",
    Households_supplied: "80,000",
  },
  {
    id: 9,
    type: "solar",
    title: "Kiamal Solar Farm",
    img: Kiamal,
    description: `In Ouyen, Victoria, Australia, a significant solar power project is currently under construction, covering an expansive area of 1000 hectares. This project features a one-axis tracker system and is designed to achieve a peak power output of 200 MWp and a nominal power of 148 MWn. Once operational, the plant is expected to produce approximately 420,000 MWh of electricity annually. This output will substantially reduce carbon emissions, avoiding around 320,000 tons of CO₂ each year. Additionally, the generated power will be sufficient to supply electricity to approximately 80,000 households, marking a considerable contribution to sustainable energy in the region.`,
    location: "Ouyen, Victoria, Australia",
    Country: "Australia",
    Region: "Ouyen, Victoria",
    Area: "1000ha",
    Project_status: "In Construction",
    System_type: "One Axis Tracker",
    Peak_power: "200MWp",
    Nominal_power: "148MWn",
    Annual_production: "420,000MWh/year",
    Tons_of_CO2_avoided: "320,000tons CO₂/year",
    Households_supplied: "80,000",
  },
  {
    id: 10,
    type: "solar",
    title: "Wughnu Solar Farm",
    img: Wughnu,
    description: `In Chinchilla, Australia, a significant solar power project is currently under construction, covering an expansive area of 1000 hectares. This project features a one-axis tracker system and is designed to achieve a peak power output of 200 MWp and a nominal power of 148 MWn. Once operational, the plant is expected to produce approximately 188,300 MWh of electricity annually. This output will substantially reduce carbon emissions, avoiding around 320,000 tons of CO₂ each year. Additionally, the generated power will be sufficient to supply electricity to approximately 27,152 households, marking a considerable contribution to sustainable energy in the region.`,
    location: "Chinchilla, Australia",
    Country: "Australia",
    Region: "Chinchilla",
    Area: "1000ha",
    Project_status: "In Construction",
    System_type: "One Axis Tracker",
    Peak_power: "200MWp",
    Nominal_power: "148MWn",
    Annual_production: "188,300MWh/year",
    Tons_of_CO2_avoided: "320,000tons CO₂/year",
    Households_supplied: "27,152",
  },
  {
    id: 11,
    type: "battery",
    title: "Blacktop Bess Farm",
    img: Blacktop,
    description: `In Chinchilla, Australia, a significant battery energy storage system (BESS) project named Blacktop is currently under construction. Covering an area of 552 hectares, this project will have an installed capacity of 200 MW. It features a one-axis tracker system designed to optimize its performance. Once operational, Blacktop is expected to play a crucial role in stabilizing the region's energy supply, supporting grid integration, and enhancing renewable energy utilization.`,
    location: "Chinchilla, Australia",
    Country: "Australia",
    Region: "Chinchilla",
    Area: "552ha",
    Project_status: "In Construction",
    System_type: "One Axis Tracker",
    Peak_power: "200MWp",
    Nominal_power: "148MWn",
    Annual_production: "420,000MWh/year",
    Tons_of_CO2_avoided: "320,000tons CO₂/year",
    Households_supplied: "80,000",
  },
  {
    id: 12,
    type: "battery",
    title: "Deniliquin Bess Farm",
    img: Deniliquin,
    description: `In Deniliquin, Australia, a significant battery energy storage system (BESS) project is under construction. Covering an area of 552 hectares, this project will have an installed capacity of 195 MW. It features a one-axis tracker system designed to optimize its performance. Once operational, Deniliquin will enhance the reliability of the regional power grid, ensuring stable energy supply and supporting renewable energy integration.`,
    location: "Deniliquin, Australia",
    Country: "Australia",
    Region: "Deniliquin",
    Area: "552ha",
    Project_status: "In Construction",
    System_type: "One Axis Tracker",
    Peak_power: "200MWp",
    Nominal_power: "148MWn",
    Annual_production: "420,000MWh/year",
    Tons_of_CO2_avoided: "320,000tons CO₂/year",
    Households_supplied: "80,000",
  },
  {
    id: 13,
    type: "battery",
    title: "Direk Bess Farm",
    img: Direk,
    description: `In Chinchilla, Australia, a significant battery energy storage system (BESS) project named Direk is currently under construction. Covering an area of 552 hectares, this project will have an installed capacity of 200 MW. It features a one-axis tracker system designed to optimize its performance. Once operational, Direk will contribute to stabilizing the regional grid, improving energy reliability, and supporting the integration of renewable energy sources.`,
    location: "Chinchilla, Australia",
    Country: "Australia",
    Region: "Chinchilla",
    Area: "552ha",
    Project_status: "In Construction",
    System_type: "One Axis Tracker",
    Peak_power: "200MWp",
    Nominal_power: "148MWn",
    Annual_production: "420,000MWh/year",
    Tons_of_CO2_avoided: "320,000tons CO₂/year",
    Households_supplied: "80,000",
  },
  {
    id: 14,
    type: "battery",
    title: "Finley Bess Farm",
    img: Finley,
    description: `In Chinchilla, Australia, a significant battery energy storage system (BESS) project named Finley is currently under construction. Covering an area of 552 hectares, this project will have an installed capacity of 200 MW. It features a one-axis tracker system designed to optimize its performance. Once operational, Finley will enhance the stability of the regional electricity grid, ensuring reliable energy supply and supporting the integration of renewable energy sources.`,
    location: "Chinchilla, Australia",
    Country: "Australia",
    Region: "Chinchilla",
    Area: "552ha",
    Project_status: "In Construction",
    System_type: "One Axis Tracker",
    Peak_power: "200MWp",
    Nominal_power: "148MWn",
    Annual_production: "420,000MWh/year",
    Tons_of_CO2_avoided: "320,000tons CO₂/year",
    Households_supplied: "80,000",
  },

  {
    id: 15,
    type: "battery",
    title: "Whylla Bess Farm",
    img: Whylla,
    description: `In Chinchilla, Australia, a significant battery energy storage system (BESS) project named Whylla is currently under construction. Covering an area of 1000 hectares, this project will have an installed capacity of 330 MW. It features a one-axis tracker system designed to optimize its performance. Once operational, Whylla will play a key role in enhancing grid stability, ensuring reliable electricity supply, and supporting the integration of renewable energy technologies.`,
    location: "Chinchilla, Australia",
    Country: "Australia",
    Region: "Chinchilla",
    Area: "1000ha",
    Project_status: "In Construction",
    System_type: "One Axis Tracker",
    Peak_power: "200MWp",
    Nominal_power: "148MWn",
    Annual_production: "420,000MWh/year",
    Tons_of_CO2_avoided: "320,000tons CO₂/year",
    Households_supplied: "80,000",
  },
  {
    id: 16,
    type: "battery",
    title: "Foster Bess Farm",
    img: Foster,
    description: `In Chinchilla, Australia, a significant battery energy storage system (BESS) project named Foster is currently under construction. Covering an area of 1000 hectares, this project will have an installed capacity of 330 MW. It features a one-axis tracker system designed to optimize its performance. Once operational, Foster will contribute to grid stability, ensuring reliable energy supply and supporting the region's transition to renewable energy sources.`,
    location: "Chinchilla, Australia",
    Country: "Australia",
    Region: "Chinchilla",
    Area: "1000ha",
    Project_status: "In Construction",
    System_type: "One Axis Tracker",
    Peak_power: "200MWp",
    Nominal_power: "148MWn",
    Annual_production: "420,000MWh/year",
    Tons_of_CO2_avoided: "320,000tons CO₂/year",
    Households_supplied: "80,000",
  },
  {
    id: 17,
    type: "battery",
    title: "Jindera Bess Farm",
    img: Jindera,
    description: `In Chinchilla, Australia, a significant battery energy storage system (BESS) project named Jindera is currently under construction. Covering an area of 1000 hectares, this project will have an installed capacity of 330 MW. It features a one-axis tracker system designed to optimize its performance. Once operational, Jindera will enhance grid stability, ensuring reliable electricity supply and supporting the integration of renewable energy technologies.`,
    location: "Chinchilla, Australia",
    Country: "Australia",
    Region: "Chinchilla",
    Area: "1000ha",
    Project_status: "In Construction",
    System_type: "One Axis Tracker",
    Peak_power: "200MWp",
    Nominal_power: "148MWn",
    Annual_production: "420,000MWh/year",
    Tons_of_CO2_avoided: "320,000tons CO₂/year",
    Households_supplied: "80,000",
  },
  {
    id: 18,
    type: "battery",
    title: "Penfield Bess Farm",
    img: Penfield,
    description: `In Chinchilla, Australia, a significant battery energy storage system (BESS) project named Penfield is currently under construction. Covering an area of 1000 hectares, this project will have an installed capacity of 330 MW. It features a one-axis tracker system designed to optimize its performance. Once operational, Penfield will contribute to grid stability, ensuring reliable energy supply and supporting the region's transition to renewable energy sources.`,
    location: "Chinchilla, Australia",
    Country: "Australia",
    Region: "Chinchilla",
    Area: "1000ha",
    Project_status: "In Construction",
    System_type: "One Axis Tracker",
    Peak_power: "200MWp",
    Nominal_power: "148MWn",
    Annual_production: "420,000MWh/year",
    Tons_of_CO2_avoided: "320,000tons CO₂/year",
    Households_supplied: "80,000",
  },
];
